refactor(restaurant-models): change the type of Restaurant models fie…
SodokinMarius/RestaurantAPI-USING-JWT-AUTHENTICATION pull request #1
Opened 2022-08-31 16:09 UTC by SodokinMarius

…lds into FloatField

2022-09-01 09:46 UTC, koladev32 commented
- Le nom du PR n'a pas été modifié

2022-09-01 09:47 UTC, koladev32 commented
Et ce refactoring concerne uniquement les restaurants models non? Pourquoi ajouter les tests déjà?

2022-09-01 09:48 UTC, koladev32 commented
Il y a 4 commits et 15 fichier changés? Comment suivre cela?

2022-09-04 21:51 UTC, koladev32 requested changes

2022-09-04 21:51 UTC, koladev32 commented on restaurant/views.py
>  from django.http import Http404
This file should be deleted

2022-09-04 21:51 UTC, koladev32 commented on authentification/viewsets.py
> +class LoginViewSet(ModelViewSet):
You should precise the only allowed methods here

2022-09-04 21:51 UTC, koladev32 commented on authentification/viewsets.py
> +class SignupViewSet(ModelViewSet):
Good job

2022-09-04 21:51 UTC, koladev32 commented on authentification/viewsets.py
> +        return Response(data=serializer.errors,status=status.HTTP_400_BAD_REQUEST)
No need for that. serializer.is_valid(raise_exception=True) will work for that

2022-09-04 21:51 UTC, koladev32 commented on authentification/viewsets.py
> +        return  Response(data=serializer.errors,status_code=status.HTTP_400_BAD_REQUEST)
You can remove this line and just call the raise_exception

2022-09-04 21:51 UTC, koladev32 commented on restaurant/urls.py
> +routeur.register('restaurants',RestaurantViewSet,basename='restaurants-list')
Not a great name for the router

2022-09-04 21:51 UTC, koladev32 commented on restaurant/urls.py
> +routeur=SimpleRouter()
it will be `router` and not `routeur` as we are going in english

2022-09-04 21:52 UTC, koladev32 requested changes
Good job in general. Correct the reviews and merge it.

2022-09-05 01:50 UTC, koladev32 commented
Merge the code

2022-09-05 02:29 UTC, merged

2022-09-05 02:30 UTC, SodokinMarius commented
ok, thanks for all comments and suggestions. I've already done all.